# Nome do Workflow
name: CI - Verificação de Qualidade e Build

# Gatilhos: Quando o workflow deve rodar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs: As tarefas a serem executadas
jobs:
  quality-and-build-checks:
    # O tipo de máquina virtual para rodar o job
    runs-on: ubuntu-latest

    # Passos sequenciais do job
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instala as dependências (de todos os arquivos, para validar)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ml_jobs/requirements-jobs.txt
          pip install -r frontend/requirements-frontend.txt
          pip install ruff # Instala a ferramenta de linting

      # 4. Verifica a qualidade do código com Ruff
      - name: Lint with Ruff
        run: |
          ruff check .

      # 5. Valida o build da imagem Docker da API
      - name: Build API Docker image
        run: |
          docker build -t api-test -f api/Dockerfile .
      
      # 6. Valida o build da imagem Docker dos Jobs de ML
      - name: Build ML Jobs Docker image
        run: |
          docker build -t ml-jobs-test -f ml_jobs/Dockerfile .
