
name: CI/CD Pipeline - Predictor Fut BR


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar qualidade do código com Ruff
        run: |
          pip install ruff
          ruff check . --output-format=github
          
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # 'false' significa que vamos apenas construir, sem enviar para um registro
          tags: bolinhx/predictor-fut-br:latest 